<!-- <img src="files/images/python-screenshot.jpg" width="600"> -->
<img src="imgs/header.png">

## Basics of Numerical Python Arrays (numpy)

### 1. In-place Arithmetics

In [20]:
import numpy as np

#### Case 1: a = a+b 
The sum is first computed and resulting in a new array and the a is bound to the new array

In [22]:
a = np.array(range(10000000))
b = np.array(range(9999999,-1,-1))
print(a)
print(b)

[      0       1       2 ..., 9999997 9999998 9999999]
[9999999 9999998 9999997 ...,       2       1       0]


In [25]:
%%time
c = a + b
print(c)

[9999999 9999999 9999999 ..., 9999999 9999999 9999999]
CPU times: user 23.2 ms, sys: 13.5 ms, total: 36.7 ms
Wall time: 35 ms


#### Case 2: a += b 
The elements of b are directly added into the elements of a (in memory) - no intermediate array. These operators implement the so-called "in-place arithmetics" (e.g., +=, *=, /=, -= )  

In [ ]:
a = np.array(range(10000000))
b = np.array(range(9999999,-1,-1))

In [26]:
%%time
a +=b 

CPU times: user 14.2 ms, sys: 990 µs, total: 15.1 ms
Wall time: 13.7 ms


### 2. Vectorization

In [29]:
#Apply function to a complete array instead of writing loop to iterate over all elements of the array. 
#This is called vectorization. The opposite of vectorization (for loops) is known as the scalar implementation

def f(x):
    return x*np.exp(4)

print(f(a))

[  5.45981446e+08   5.45981446e+08   5.45981446e+08 ...,   5.45981446e+08
   5.45981446e+08   5.45981446e+08]


### 3. Slicing and reshape

#### Array slicing
    x[i:j:s] 
picks out the elements starting with index i and stepping s indices at the time up to, but not including, j.

Take into account that -1 is the last element (think of it as going backwards)

In [40]:
x = np.array(range(100))
#print(x)
q = x[1:-1] # picks out all elements except the first and the last, but contrary to lists, a[1:-1] is not a copy of the data in a.
print(q)
p = x[0:-1:2] # picks out every two elements up to, but not including the last element
print(p)
w = x[0:len(x):3] # picks out every three elements up to the last element (explicit)
print(w)
z = x[0::3] # picks out every three elements up to the last element (implicit)
print(z)
x[::4] # picks out every four elements in the whole array.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

#### Array shape manipulation

We can transform the array into a vector of more dimensions while preserving the number of elements inside the vector

In [48]:
a = np.linspace(-1, 1, 6) #returns 6 numbers inside the inclusive range given by the first two parameters
print (a)

a.shape
a.size

# rows, columns
a.shape = (2, 3) 
#a = a.reshape(2, 3) # alternative

print(a.shape)
print (a)

# len(a) always returns the length of the first dimension of an array. -> no. of rows

[-1.  -0.6 -0.2  0.2  0.6  1. ]
(2, 3)
[[-1.  -0.6 -0.2]
 [ 0.2  0.6  1. ]]


## Exercise
### 1. Create a 10x10 2d array with 1 on the border and 0 inside

In [50]:
Z = np.ones((10,10)) # similar to matlab
Z[1:-1,1:-1] = 0 # up until, but not including, the last element in both dimensions
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### 2. Create a structured array representing a position (x,y) and a color (r,g,b)

Docs here: https://docs.scipy.org/doc/numpy/user/basics.rec.html

In [67]:
Z = np.zeros(3, [ ('position', [ ('x_vector', int, 2),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)
print(type(Z))


print("-----------------------------------------")

J = [ ('position', [ ('x_vector', int, 2),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])]
print(J)
print(type(J))

[(([0, 0], 0.0), (0.0, 0.0, 0.0)) (([0, 0], 0.0), (0.0, 0.0, 0.0))
 (([0, 0], 0.0), (0.0, 0.0, 0.0))]
<type 'numpy.ndarray'>
-----------------------------------------
[('position', [('x_vector', <type 'int'>, 2), ('y', <type 'float'>, 1)]), ('color', [('r', <type 'float'>, 1), ('g', <type 'float'>, 1), ('b', <type 'float'>, 1)])]
<type 'list'>


### 3. Consider a large vector Z, compute Z to the power of 3 using 2 different methods

In [ ]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x